version: '3'
services:
  uploader:
   image: kcapd/publisher
   entrypoint: /go/bin/transfersh --provider local --basedir /files --listener :8080 --http-auth-user ${TRANSFER_USER} --http-auth-pass ${TRANSFER_PASSWORD}  --web-path /web
   restart: always
   volumes:
      - ./files:/files
      - ./dist:/web
   ports:
      - "7071:8080"
volumes:
   files:
